# Theme Github link: https://github.com/korilin/hexo-theme-particle
# Developer: korilin

# html lang
language: zh

# avatar image url
head_img: images/avatar.jpeg

# home page head info block
head_block_enable: true

# home page head background style.
# If you use a picture as background, you must use the css background-image attribute instead of the background attribute.
# Use image as background ==> home_background: "background-image:url('../home.jpg')"
# Use a color as background ==> home_background: "background: balck"
home_background: "background-image:url('home.jpg')"

# Particle theme icon is adopts the ant design vue icons
# Link：https://www.antdv.com/components/icon-cn/

# main menu navigation
menu:
  home:
    icon:
      name: home
      theme: filled
    src: /cindeyChen.github.io/
  about:
    icon:
      name: idcard
      theme: filled
    src: /about # 当你的博客root为 '/' 时
  archives:
    icon:
      name: folder
      theme: filled
    src: /archives
  categories:
    icon:
      name: book
      theme: filled
    src: /like/categories # 当你的博客root不为 '/'，而是其它时，例如 '/like/'
  tags:
    icon:
      name: tags
      theme: filled
    src: /like/tags

# side info card
card:
  enable: true
  description: ["前端开发"]
  icon_links:
    github:
      icon:
        type: antd-icon
        name: github
        theme: filled
        src:
      link: https://github.com/ZhenhuaChen
  friend_links:
    简书: https://www.jianshu.com/u/c845488754ed
    掘金: https://juejin.cn/user/1979583091713656/posts

# footer info
footer:
  since: 2018
  # Customize the server domain name ICP
  ICP:
    enable: false
    code: 

# Gitalk
# https://github.com/gitalk/gitalk
gitalk:
  enable: true
  clientID: # GitHub Application Client ID
  clientSecret: # GitHub Application Client Secret
  repo: hexo-theme-particle # The name of repository of store comments
  owner: Cindey # GitHub repo owner
  admin: Cindey # GitHub repo owner and collaborators, only these guys can initialize github issues
  language: en # en, zh-CN, zh-TW, es-ES, fr, ru, de, pl and ko are currently available.

# theme style: full / night / maiden, defalut: full
style: maiden
